---
title: "Freeland Bunker Analysis"
output: html_document
date: "2023-07-28"
name: "Delphine Demais and Will Draxler"
---

```{r install.packages}
#chooseCRANmirror(ind=70)
#install.packages("readxl")
library(readxl)
library(tidyverse)
library(tidytext)
library(ggplot2)
library(stringr)
library(dplyr)
library(textclean)
library(stopwords)
```

## Read Excel Freeland Bunker Journal Transcription (1873-1874)

```{r read_excel}
journal_1873 <- read_excel("data/journal_1873.xlsx")
journal_1874 <- read_excel("data/journal_1874.xlsx")
```

```{r month_1873}
journal_1873 <- journal_1873 %>% 
  rename(month = date)
```

## Exploratory Visualizations

### Wind Speed 1873
```{r wind_speed_1873_pivot_longer}
wind_speed_1873 <- journal_1873 %>%
  select(date_mdy,
         month,
         wind_speed_am, 
         wind_speed_pm, 
         wind_speed_night) %>% 
  mutate(year = "1873") %>% 
  pivot_longer(cols = starts_with("wind_speed"), 
               names_to = "period", 
               values_to = "wind_speed") %>%
  mutate(period = case_when(
    period == "wind_speed_am" ~ "am",
    period == "wind_speed_pm" ~ "pm", 
    period == "wind_speed_night" ~ "night")) %>% 
  separate_rows(wind_speed, sep = ",") %>% 
  mutate(category = case_when(
    wind_speed %in% c("blustering", "very blustering") ~ "blustering",
    wind_speed %in% c("breezy", "good breeze", "very fresh breeze", "breezed up", "fresh breeze", "heavy breeze", "smart breeze", "strong breeze") ~ "breeze",
    wind_speed %in% c("blowing very heavy", "fresh blow", "heavy blow", "very heavy blow", "blowy", "blowing", "blowing hard", "blowing very hard") ~ "blow",
    wind_speed %in% c("fresh gale", "gale") ~ "gale",
    wind_speed %in% c("moderate", "quite moderate", "very moderate") ~ "moderate",
    wind_speed %in% c("pleasant", "quite pleasant", "very pleasant") ~ "pleasant",
    wind_speed %in% c("calm", "perfectly calm") ~ "calm",
    wind_speed %in% c("scant wind", "heavy winds") ~ "wind",
    wind_speed %in% c("rough", "squall", "strong", "very light", "heavy", "baffling", "a light air", "variable", "fair") ~ "other intensities"
  ))
```

```{r bar_wind_speed_frequency_1873}
wind_speed_1873 %>%
  mutate(wind_speed = ifelse(wind_speed == "NA", NA, wind_speed)) %>%
  drop_na(wind_speed, period, category) %>%
  group_by(wind_speed, period, category) %>%
  summarize(n = n()) %>%
  mutate(period = factor(period, levels = c("am", "pm", "night"))) %>%
  ggplot(aes(x = wind_speed, 
             y = n, 
             fill = category)) +
  geom_bar(stat = "identity", 
           position = "dodge") +
  labs(title = "Wind Vocabulary Frequency by Period of the Day 1873",
       x = "Wind Speed Vocabulary", 
       y = "Frequency", 
       fill = "Category") +
  theme_minimal() +
  coord_flip() +
  facet_wrap(~ period)
```
```{r coodpolar_wind_speed_frequency_1873, fig.height=5, fig.width=10}
  wind_speed_1873 %>%
  mutate(wind_speed = ifelse(wind_speed == "NA", NA, wind_speed)) %>%
  drop_na(wind_speed, period, category) %>%
  group_by(wind_speed, period, category) %>%
  summarize(n = n()) %>%
  mutate(period = factor(period, levels = c("am", "pm", "night"))) %>%
  ggplot(aes(x = wind_speed, 
             y = n, 
             fill = category)) +
  geom_bar(stat = "identity", 
           position = "dodge") +
  labs(title = "General Wind Vocabulary Frequency 1873",
       x = "Wind Speed Vocabulary", 
       y = "Frequency", 
       fill = "Category") +
  theme_minimal() +
  coord_polar() +
  scale_y_log10() # to better see smaller frequencies
```
```{r piechart_wind_speed_frequency_1873}
wind_speed_1873 %>%
  mutate(wind_speed = ifelse(wind_speed == "NA", NA, wind_speed)) %>%
  drop_na(wind_speed, period, category) %>%
  group_by(wind_speed, period, category) %>%
  summarize(n = n()) %>%
  mutate(period = factor(period, levels = c("am", "pm", "night"))) %>%
  ggplot(aes(x = "", y = n, fill = category)) +
  geom_bar(stat = "identity", width = 1) + # 1 for pie chart effect
  labs(x = NULL, y = "Frequency", fill = "Category") +
  theme_minimal() +
  coord_polar("y", start = 0) +
  theme_void() +
  labs(title = " 1873 Wind Vocabulary by Category")
```

### Wind Speed Comparison 1873-1874

```{r wind_speed_1874_pivot_longer}
wind_speed_1874 <- journal_1874 %>%
  select(date_mdy, 
         month,
         wind_speed_am, 
         wind_speed_pm, 
         wind_speed_night) %>% 
  mutate(year = 1874) %>% 
  pivot_longer(cols = starts_with("wind_speed"), 
               names_to = "period", 
               values_to = "wind_speed") %>%
  mutate(period = case_when(
    period == "wind_speed_am" ~ "am",
    period == "wind_speed_pm" ~ "pm", 
    period == "wind_speed_night" ~ "night")) %>% 
  separate_rows(wind_speed, sep = ",") %>% 
  mutate(category = case_when(
    wind_speed %in% c("blustering", "very blustering") ~ "blustering",
    wind_speed %in% c("breezy", "good breeze", "very fresh breeze", "breezed up", "fresh breeze", "heavy breeze", "smart breeze", "strong breeze") ~ "breeze",
    wind_speed %in% c("blowing very heavy", "fresh blow", "heavy blow", "very heavy blow", "blowy", "blowing", "blowing hard", "blowing very hard") ~ "blow",
    wind_speed %in% c("fresh gale", "gale") ~ "gale",
    wind_speed %in% c("moderate", "quite moderate", "very moderate") ~ "moderate",
    wind_speed %in% c("pleasant", "quite pleasant", "very pleasant") ~ "pleasant",
    wind_speed %in% c("calm", "perfectly calm") ~ "calm",
    wind_speed %in% c("scant wind", "heavy winds") ~ "wind",
    wind_speed %in% c("rough", "squall", "strong", "very light", "heavy", "baffling", "a light air", "variable", "fair") ~ "other intensities"
  ))
```

```{r combine_wind_speed}
combined_wind_speed<- rbind(wind_speed_1873, wind_speed_1874)
```

```{r wind_speed_comparison}
combined_wind_speed %>%
  mutate(wind_speed = ifelse(wind_speed == "NA", NA, wind_speed)) %>%
  drop_na(wind_speed, period, category, year) %>%
  group_by(wind_speed, category, year) %>%
  summarize(n = n()) %>%
  ggplot(aes(x = wind_speed, y = n, fill = category)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Yearly Comparison of Wind Speed Vocabulary",
       subtitle = "Colored by Overarching Categories in 1873 and 1874",
       x = "Wind Speed Vocabulary", 
       y = "Frequency", 
       fill = "Category") +
  theme_minimal() +
  coord_flip() +
  facet_wrap(~ year)
```

```{r}
combined_wind_speed %>%
  mutate(wind_speed = ifelse(wind_speed == "NA", NA, wind_speed)) %>%
  drop_na(wind_speed, period, category, year) %>%
  group_by(category, month, year) %>%
  summarise(frequency = n()) %>%
  ggplot(aes(x = category, y = frequency, fill = as.factor(year))) +
  geom_bar(stat = "identity", position = "stack") +
  labs(title = "Monthly Comparison of Wind Speed Categories 1873-1874",
       x = "Category",
       y = "Frequency",
       fill = "Year") +
  facet_wrap(~ month) +
  coord_flip()
```

### Wind Directions 1873
```{r wind_direction_function}
convert_wind_direction_to_degrees <- function(wind_direction) {
  degrees <- case_when(
    wind_direction == "N" ~ 0,
    wind_direction == "NNE" ~ 22.5,
    wind_direction == "NE" ~ 45,
    wind_direction == "ENE" ~ 67.5,
    wind_direction == "E" ~ 90,
    wind_direction == "ESE" ~ 112.5,
    wind_direction == "SE" ~ 135,
    wind_direction == "SSE" ~ 157.5,
    wind_direction == "S" ~ 180,
    wind_direction == "SSW" ~ 202.5,
    wind_direction == "SW" ~ 225,
    wind_direction == "WSW" ~ 247.5,
    wind_direction == "W" ~ 270,
    wind_direction == "WNW" ~ 292.5,
    wind_direction == "NW" ~ 315,
    wind_direction == "NNW" ~ 337.5,
    TRUE ~ NA_real_  # Return NA if the wind direction is not recognized
  )
  return(degrees)
}
```

```{r wind_direction_longer_1873}
wind_direction_1873_long <- journal_1873 %>% 
  pivot_longer(cols = starts_with("wind_direction"), 
               names_to = "period", 
               values_to = "wind_direction") %>% 
  separate_rows(wind_direction, sep = ", ") %>% 
  mutate(period = case_when(
    period == "wind_direction_am" ~ "am",
    period == "wind_direction_pm" ~ "pm", 
    period == "wind_direction_night" ~ "night"
  ))
```

```{r 1873_mutate_degrees}
wind_direction_1873_long <- wind_direction_1873_long %>%
  mutate(
    wind_degrees = case_when(
      period == "am" ~ convert_wind_direction_to_degrees(wind_direction),
      period == "pm" ~ convert_wind_direction_to_degrees(wind_direction),
      period == "night" ~ convert_wind_direction_to_degrees(wind_direction)
    )) %>% 
  select(date_mdy, month, wind_direction, period, wind_degrees) %>% 
  mutate(year = "1873")
```

```{r 1873-roseplot}
# Function to convert degrees to radians for polar coordinates
to_radians <- function(degrees) {
  return((degrees - 90) * pi / 180)
}

wind_direction_1873_long %>% 
  ggplot(aes(x = to_radians(wind_degrees))) +
  geom_bar(aes(fill = stat(count)), 
           bins = 16, 
           color = "black") +  
  scale_fill_viridis_c(option = "plasma", name = "Frequency") + 
  geom_text(aes(x = to_radians(wind_degrees), 
                y = 150, label = wind_direction),
            size = 4, fontface = "bold", 
            color = "black") +  
  labs(title = "Wind Directions Mentionned, 1873", 
       "Only Directions Explicitely Specified by Period",
       x = NULL, 
       y = NULL) +
  theme_minimal() +
  theme(axis.text = element_blank()) +
  coord_polar() +
  scale_y_continuous(name = "Frequency", 
                     trans = "log10")   # Frequency scale (logarithmic)
```

```{r period_rose_plot, fig.height=10, fig.width=15}
wind_direction_1873_long %>% 
  mutate(period = factor(period, levels = c("am", "pm", "night"))) %>%
  ggplot(aes(x = to_radians(wind_degrees))) +
  geom_bar(aes(fill = stat(count)), 
           bins = 16, 
           color = "black") +  
  scale_fill_viridis_c(option = "plasma", name = "Frequency") + 
  geom_text(aes(x = to_radians(wind_degrees), 
                y = 150, label = wind_direction),
            size = 4, fontface = "bold", 
            color = "black") +  
  labs(title = "Wind Directions Mentionned by Period of the Day, 1873", 
       x = NULL, 
       y = NULL) +
  theme_minimal() +
  theme(axis.text = element_blank()) +
  coord_polar() +
  scale_y_continuous(name = "Frequency", 
                     trans = "log10") +  # Frequency scale (logarithmic)
  facet_wrap(~ period)
```
```{r month-rose-plot, fig.height=8, fig.width=15}
wind_direction_1873_long %>% 
  ggplot(aes(x = to_radians(wind_degrees))) +
  geom_bar(aes(fill = stat(count)), 
           bins = 16, 
           color = "black") + 
  scale_fill_viridis_c(option = "plasma", name = "Frequency") + 
  geom_text(aes(x = to_radians(wind_degrees), 
                y = 150, label = wind_direction),
            size = 4, fontface = "bold", 
            color = "black") +  
  labs(title = "Wind Directions Mentioned by Month, 1873",
       x = NULL, 
       y = NULL) +
  theme_minimal() +
  theme(axis.text = element_blank()) +
  coord_polar() +
  scale_y_continuous(name = "Frequency", 
                     trans = "log10") +  # Frequency scale (logarithmic)
  facet_wrap(~ month)
```


```{r wind_direction_frequency, fig.height=10, fig.width=20}
wind_direction_1873_long %>% 
 mutate(wind_direction = ifelse(wind_direction == "NA", NA, wind_direction)) %>%
  mutate(period = factor(period, levels = c("am", "pm", "night"))) %>%
  drop_na(wind_direction, period, month) %>%
  ggplot(aes(x = wind_direction, fill = period)) +
  geom_bar(position = "stack", color = "black") +
  labs(title = "Bar Chart of Monthly Wind Directions Frequencies in 1873",
       x = "Wind Direction",
       y = "Frequency") +
  coord_flip() +
  facet_wrap(~ month, nrow = 2)
```

### Wind Direction Comparison 1873-1874
```{r longer_wind_direction_1874}
wind_direction_1874_long <- journal_1874 %>% 
  pivot_longer(cols = starts_with("wind_direction"), 
               names_to = "period", 
               values_to = "wind_direction") %>% 
  separate_rows(wind_direction, sep = ", ") %>% 
  mutate(period = case_when(
    period == "wind_direction_am" ~ "am",
    period == "wind_direction_pm" ~ "pm", 
    period == "wind_direction_night" ~ "night"
  ))
```

```{r 1874_mutate_degrees}
wind_direction_1874_long <- wind_direction_1874_long %>%
  mutate(
    wind_degrees = case_when(
      period == "am" ~ convert_wind_direction_to_degrees(wind_direction),
      period == "pm" ~ convert_wind_direction_to_degrees(wind_direction),
      period == "night" ~ convert_wind_direction_to_degrees(wind_direction)
    )) %>% 
  select(date_mdy, month, wind_direction, period, wind_degrees) %>% 
  mutate(year = "1874") 
```

```{r combine_wind-direction}
combined_wind_direction <- rbind(wind_direction_1873_long, wind_direction_1874_long)
```

```{r wind_directinon_bar_chart}
combined_wind_direction %>% 
 mutate(wind_direction = ifelse(wind_direction == "NA", NA, wind_direction)) %>%
  drop_na(wind_direction, period, year) %>%
  ggplot(aes(x = wind_direction, fill = year)) +
  geom_bar(position = "stack", color = "black") +
  labs(title = "Bar Chart of Yearly Wind Directions Frequencies",
       x = "Wind Direction",
       y = "Frequency") +
  coord_flip() 
```

### Letters

```{r change_reed_to_recd}
journal_1873 <- journal_1873 %>%
  mutate(letter = case_when(
    letter == "read" ~ "received",
    letter == "read and write" ~ "received and write",
    TRUE ~ letter  # Keep the original value if none of the conditions match
  ))

journal_1874 <- journal_1874 %>%
  mutate(letter = case_when(
    letter == "read" ~ "received",
    letter == "read and write" ~ "received and write",
    TRUE ~ letter  # Keep the original value if none of the conditions match
  ))
```

```{r letter_df}
letters_1873 <- journal_1873 %>%
  select(date_mdy, month, journal_entry, letter, notes) %>% 
  mutate(year = "1873")

letters_1874 <- journal_1874 %>%
  select(date_mdy, month, journal_entry, letter, notes) %>% 
  mutate(year = "1874")
```

```{r join_letters_df}
combined_letters <- rbind(letters_1873, letters_1874)
```

```{r letter_viz, fig.height=4, fig.width=10}
combined_letters %>%
  count(letter, year) %>%
  mutate(letter = ifelse(letter == "NA", NA, letter)) %>%
  drop_na(letter) %>%
  ggplot(aes(x = letter, 
             y = n, 
             fill = year)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~ year) +
  labs(title = "Letter Communication",
       subtitle = "For 1873 and 1874",
       x = "Letter Status",
       y = "Frequency",
       fill = "Year")
```
```{r frequency_letter}
combined_letters %>%
  mutate(letter = ifelse(letter == "NA", NA, letter)) %>%
  drop_na(letter) %>%
  filter(letter != "no letter") %>%
  count(letter, year) %>%
  ggplot(aes(x = letter, y = n, fill = year)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~ year) +
  labs(title = "Frequency of Letter Communication Mentioned",
       subtitle = "For 1873 and 1874",
       x = "Letter Status",
       y = "Frequency") +
  scale_y_continuous(breaks = seq(5, 30, 5))
```

### Communication (Names & Letters)

```{r communication_df}
#only rows with letters written or received
communication <- combined_letters %>%
  mutate(letter = ifelse(letter == "NA", NA, letter)) %>%
  drop_na(letter) %>%
  filter(letter != "no letter")
```

```{r names_mentionned_list}
#List by chatgpt from the names and their different variations in the communication table
names <- c("C.C. Burrill", "Charles C. Burrell", "Geo. N. Loomis", "GN Loomis", "Geo. W. Tracy", "Geo W Tracy", "Thomas Bunker", "T. Smallidge Boston", "Thos Bunker", "Joseph Bunker", "C. Stevens", "Reg of Deeds", "A.J. Gerrish", "Flora Gerrish", "Dresser and Ayer", "Reuben Rand", "R. Rand", "Geo.W Butler", "Geo N Loomis", "GW Butter", "G.W. Butter", "Henry W. Sargent", "T Smallidge", "Henry Geyer", "Galen Smith", "Thos Bunker Cranberry Isles", "L.D. Parsons Bangor", "SD.Parsons Bangor", "Benj Kittridge", "Benj Kittredge", "B. Kittridge", "J.T. Kingsley", "Kellly Kingsley", "E. Kingsley", "Geo A Dyer", "Arno Wiswell", "Charles C. Burrell", "Hannah Goodwin", "Charles Norris", "Nathan Goodwin", "A.G. Brooks", "Mrs FRBunker", "AN Willye", "W. B. McCrate", "James Staples", "Capt. S.L.Tracy", "Wm Joy", "William Stevens", "E. H. Wallace", "Robt Miles", "Nickerson and Rideout", "David Ames", "Joy and Hutchings", "Reg of Deeds","A.D. Crabtree")
```

```{r extract_names}
# Function to extract all names
extract_names <- function(text) {
  extracted_names <- regmatches(text, gregexpr(paste(names, collapse = "|"), text))
  return(extracted_names)
}
communication$names <- sapply(communication$journal_entry, extract_names)
```

